import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const artifacts = [
  {
    exportName: "DAPP_ABI",
    artifactPath: "artifacts/contracts/SHDStaking.sol/SHDStaking.json",
  },
  {
    exportName: "ERC20_ABI",
    artifactPath: "node_modules/@openzeppelin/contracts/build/contracts/IERC20.json",
  },
];

function readAbi({ exportName, artifactPath }) {
  const fullPath = resolve(rootDir, artifactPath);
  const artifact = JSON.parse(readFileSync(fullPath, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`${artifactPath} does not contain an ABI array`);
  }
  return `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
}

const outputPath = resolve(rootDir, "src/constants/abis/generated.ts");
const header = `/**
 * @file constants/abis/generated.ts
 * @description Auto-generated by scripts/sync-abis.mjs. Do not edit manually.
 */`;
const content = [
  header,
  ...artifacts.map(readAbi),
  "",
].join("\n\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, "utf8");
console.log(`Synced ${artifacts.length} ABIs to ${outputPath}`);